# -*- coding: utf-8 -*-
"""ParouImpar_Versus_computador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liD1hkwEW61PWgMSK_BUD7n19crc0upY
"""

import random

while True:

  print("Escolha :'P' para PAR ou 'I' para ÍMPAR: \n ")
  par_ou_impar = input("Escolha Par ou Ímpar !\n")

  if par_ou_impar != "P" and par_ou_impar != "I" :
      print("Opção inválida! Digite 'P' para PAR ou 'I' para ÍMPAR.")
  else:
      print("Você escolheu ", par_ou_impar, " ! \n")
      break

while True:

  jogador = int(input("Jogador ! digite um número entre 1 e 10: \n "))

  if jogador < 1 or jogador > 10 :

    print("Número inválido! digite novamente : \n")
  else:

    print("Jogador escolheu",jogador," \n")
    break

computador = random.randint(1,10)

print("O computador escolheu o número ",computador, " \n ")

soma = jogador + computador
teste = soma % 2

if(teste == 0 and par_ou_impar == "P") or (teste == 1 and par_ou_impar == "I"):
      print("Parabéns ! Jogador venceu! \n")
else:
      print("O computador venceu! \n")

